### ISSUE TITLE
Blank screen after login on MacOS

### ISSUE THREAD

**Issue by alayouni** [Faylixe/review.classdesign.jammy#34]
I'm under OSX El Capitain 10.11.6, Eclipse Neon.3 Release (4.6.3). After login I get a blank screen with message 'Please select a Jam contest'.

**Comment by Faylixe** [comment]
Hi again ! Yes, since Codejam UI were updated, the contest retrieval method is not working anymore, i updated the CLI application but not Jammy. Although, ID based contest selection will work, so i don't think i will update Jammy in a near feature, as i would consider moving it from Eclipse to a more generic IDE like Visual Studio Code.

If you are interested though, i will gladly accept a pull request, where googlecodejam-client version is updated.

**Comment by alayouni** [comment]
Fair enough, I don't actually use eclipse, and was going to use it just for the plugin. googlecodejam-cli serves all my needs for now so I'll just stick with it. 

With regards to googlecodejam-client, I honestly did not dig much into it and not sure what it's about exactly, but let me know what update it needs and I'll be happy to see what I can do.

Thanks again for sharing your work, your tool seems to be the only working solution shared publicly!

**Comment by Faylixe** [comment]
**googlecodejam-client** is a Java library which allows to interact with Codejam servers. It has been designed by reversing codejam API requests with Chrome console mainly. Then codejam CLI is a tools based on this library for downloading / uploading IO during contest. Jammy is a simple graphical version of it. So to update Jammy you have to update the codejam-client version to the last one, it requires some Eclipse Plugin development skills.

**Comment by alayouni** [comment]
ok got it, I unfortunately have no experience with eclipse plugin development... Intellij is my favorite IDE so I guess I'll leave this to eclipse users.
